name: publish

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')

    name: ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current version
        uses: actions/checkout@v2

      - name: Compress
        run: |
          mkdir -p release && \
          mkdir -p release/build && \
          mkdir -p release/libs && \
          mkdir -p release/public && \
          cp index.html release/ && \
          cp COPYING release/ && \
          cp README.md release/ && \
          cp build/*.* release/build/ && \
          cp libs/*.* release/libs/ && \
          cp public/*.* release/public/ && \
          cd release && \
          tar -cf ../release.tar .

      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: release.tar
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
